
name: Python Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Pyhon Build Shell
      run: ./build.py local
    - uses: actions/upload-artifact@v4
      with:
        name: iits-all-package
        path: build/local/
    - uses: actions/upload-artifact@v4
      with:
        name: total-conversion-build.user.js
        path: build/local/total-conversion-build.user.js
